// Date: 08.07.2013 16:16:50
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package me.pusty.slime.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class PustyObjectModel extends ModelBase
{
  //fields
    ModelRenderer BPlatte;
    ModelRenderer Side1;
    ModelRenderer Side2;
    ModelRenderer Side3;
    ModelRenderer Side4;
    ModelRenderer TPlatte;
    ModelRenderer Glass1;
    ModelRenderer Glass2;
    ModelRenderer Glass3;
    ModelRenderer Glass4;
  
  public PustyObjectModel()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      BPlatte = new ModelRenderer(this, 0, 0);
      BPlatte.addBox(0F, 0F, 0F, 16, 2, 16);
      BPlatte.setRotationPoint(-8F, 22F, -8F);
      BPlatte.setTextureSize(64, 32);
      BPlatte.mirror = true;
      setRotation(BPlatte, 0F, 0F, 0F);
      Side1 = new ModelRenderer(this, 0, 18);
      Side1.addBox(0F, 0F, 0F, 1, 12, 1);
      Side1.setRotationPoint(7F, 10F, 7F);
      Side1.setTextureSize(64, 32);
      Side1.mirror = true;
      setRotation(Side1, 0F, 0F, 0F);
      Side2 = new ModelRenderer(this, 0, 18);
      Side2.addBox(0F, 0F, 0F, 1, 12, 1);
      Side2.setRotationPoint(7F, 10F, -8F);
      Side2.setTextureSize(64, 32);
      Side2.mirror = true;
      setRotation(Side2, 0F, 0F, 0F);
      Side3 = new ModelRenderer(this, 0, 18);
      Side3.addBox(0F, 0F, 0F, 1, 12, 1);
      Side3.setRotationPoint(-8F, 10F, -8F);
      Side3.setTextureSize(64, 32);
      Side3.mirror = true;
      setRotation(Side3, 0F, 0F, 0F);
      Side4 = new ModelRenderer(this, 0, 18);
      Side4.addBox(0F, 0F, 0F, 1, 12, 1);
      Side4.setRotationPoint(-8F, 10F, 7F);
      Side4.setTextureSize(64, 32);
      Side4.mirror = true;
      setRotation(Side4, 0F, 0F, 0F);
      TPlatte = new ModelRenderer(this, 0, 0);
      TPlatte.addBox(0F, 0F, 0F, 16, 2, 16);
      TPlatte.setRotationPoint(-8F, 8F, -8F);
      TPlatte.setTextureSize(64, 32);
      TPlatte.mirror = true;
      setRotation(TPlatte, 0F, 0F, 0F);
      Glass1 = new ModelRenderer(this, 36, 6);
      Glass1.addBox(0F, 0F, 0F, 0, 12, 14);
      Glass1.setRotationPoint(-7F, 10F, -7F);
      Glass1.setTextureSize(64, 32);
      Glass1.mirror = true;
      setRotation(Glass1, 0F, 0F, 0F);
      Glass2 = new ModelRenderer(this, 36, 6);
      Glass2.addBox(0F, 0F, 0F, 0, 12, 14);
      Glass2.setRotationPoint(7F, 10F, -7F);
      Glass2.setTextureSize(64, 32);
      Glass2.mirror = true;
      setRotation(Glass2, 0F, 0F, 0F);
      Glass3 = new ModelRenderer(this, 36, 20);
      Glass3.addBox(0F, 0F, 0F, 14, 12, 0);
      Glass3.setRotationPoint(-7F, 10F, 7F);
      Glass3.setTextureSize(64, 32);
      Glass3.mirror = true;
      setRotation(Glass3, 0F, 0F, 0F);
      Glass4 = new ModelRenderer(this, 36, 20);
      Glass4.addBox(0F, 0F, 0F, 14, 12, 0);
      Glass4.setRotationPoint(-7F, 10F, -7F);
      Glass4.setTextureSize(64, 32);
      Glass4.mirror = true;
      setRotation(Glass4, 0F, 0F, 0F);
  }
  
  public void renderModel(float f5,boolean b)
  {
	    if(!b)
	    BPlatte.render(f5);
	    Side1.render(f5);
	    Side2.render(f5);
	    Side3.render(f5);
	    Side4.render(f5);
	    TPlatte.render(f5);
	    Glass1.render(f5);
	    Glass2.render(f5);
	    Glass3.render(f5);
	    Glass4.render(f5);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    BPlatte.render(f5);
    Side1.render(f5);
    Side2.render(f5);
    Side3.render(f5);
    Side4.render(f5);
    TPlatte.render(f5);
    Glass1.render(f5);
    Glass2.render(f5);
    Glass3.render(f5);
    Glass4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,e);
  }

}
