// Date: 08.07.2013 02:55:01
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package me.pusty.slime.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class PustySlimeModel extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer TobSide;
    ModelRenderer BottumSide;
    ModelRenderer Side1;
    ModelRenderer Side2;
    ModelRenderer Side3;
    ModelRenderer Side4;
    ModelRenderer Eye1;
    ModelRenderer Eye2;
  
  public PustySlimeModel()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, 0F, 0F, 16, 15, 16);
      Body.setRotationPoint(-8F, 8F, -8F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      TobSide = new ModelRenderer(this, 0, 31);
      TobSide.addBox(0F, 0F, 0F, 14, 1, 14);
      TobSide.setRotationPoint(-7F, 7F, -7F);
      TobSide.setTextureSize(64, 32);
      TobSide.mirror = true;
      setRotation(TobSide, 0F, 0F, 0F);
      BottumSide = new ModelRenderer(this, 0, 31);
      BottumSide.addBox(0F, 0F, 0F, 14, 1, 14);
      BottumSide.setRotationPoint(-7F, 23F, -7F);
      BottumSide.setTextureSize(64, 32);
      BottumSide.mirror = true;
      setRotation(BottumSide, 0F, 0F, 0F);
      Side1 = new ModelRenderer(this, 0, 31);
      Side1.addBox(0F, 0F, 0F, 1, 13, 14);
      Side1.setRotationPoint(-9F, 9F, -7F);
      Side1.setTextureSize(64, 32);
      Side1.mirror = true;
      setRotation(Side1, 0F, 0F, 0F);
      Side2 = new ModelRenderer(this, 0, 31);
      Side2.addBox(0F, 0F, 0F, 1, 13, 14);
      Side2.setRotationPoint(8F, 9F, -7F);
      Side2.setTextureSize(64, 32);
      Side2.mirror = true;
      setRotation(Side2, 0F, 0F, 0F);
      Side3 = new ModelRenderer(this, 0, 31);
      Side3.addBox(0F, 0F, 0F, 14, 13, 1);
      Side3.setRotationPoint(-7F, 9F, 8F);
      Side3.setTextureSize(64, 32);
      Side3.mirror = true;
      setRotation(Side3, 0F, 0F, 0F);
      Side4 = new ModelRenderer(this, 0, 31);
      Side4.addBox(0F, 0F, 0F, 14, 13, 1);
      Side4.setRotationPoint(-7F, 9F, -9F);
      Side4.setTextureSize(64, 32);
      Side4.mirror = true;
      setRotation(Side4, 0F, 0F, 0F);
      Eye1 = new ModelRenderer(this, 30, 46);
      Eye1.addBox(0F, 0F, 0F, 6, 1, 3);
      Eye1.setRotationPoint(-6F, 24F, 2F);
      Eye1.setTextureSize(64, 32);
      Eye1.mirror = true;
      setRotation(Eye1, 0F, 0F, 0F);
      Eye2 = new ModelRenderer(this, 30, 46);
      Eye2.addBox(0F, 0F, 0F, 6, 1, 3);
      Eye2.setRotationPoint(-6F, 24F, -5F);
      Eye2.setTextureSize(64, 32);
      Eye2.mirror = true;
      setRotation(Eye2, 0F, 0F, 0F);
  }
  
  public void renderModel(float f5,int type)
  {
    if(type==0){
    Body.render(f5);
    }
    else if(type==1){
    TobSide.render(f5);
    BottumSide.render(f5);
    Side1.render(f5);
    Side2.render(f5);
    Side3.render(f5);
    Side4.render(f5);
    }
    else if(type==2){
    Eye1.render(f5);
    Eye2.render(f5);
    }
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5,int type)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    if(type==0){
    Body.render(f5);
    }
    else if(type==1){
    TobSide.render(f5);
    BottumSide.render(f5);
    Side1.render(f5);
    Side2.render(f5);
    Side3.render(f5);
    Side4.render(f5);
    }
    else if(type==2){
    Eye1.render(f5);
    Eye2.render(f5);
    }
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,e);
  }

}
